try:
  some_function()
except Exception as the_error:
  print(the_error)
